from datetime import date


def load_daily_snapshot():
    """MVP sample data. Replace this with TWSE/TPEX/API loaders later."""
    return {
        "date": date.today().isoformat(),
        "market": {
            "taiex": {"close": 22185, "ma20": 21680, "volume_ratio": 1.18, "change_pct": 0.85},
            "otc": {"close": 251.3, "ma20": 247.6, "volume_ratio": 1.08, "change_pct": 0.42},
            "tsmc": {"symbol": "2330", "close": 872, "ma20": 850, "change_pct": 1.04},
            "limit_up_count": 38,
            "limit_down_count": 4,
        },
        "sectors": [
            {"name": "AI Server", "turnover": 1860, "limit_up_count": 8, "avg_change_pct": 3.8, "relative_volume": 1.62},
            {"name": "PCB", "turnover": 1260, "limit_up_count": 5, "avg_change_pct": 2.7, "relative_volume": 1.35},
            {"name": "Robotics", "turnover": 780, "limit_up_count": 3, "avg_change_pct": 2.2, "relative_volume": 1.28},
            {"name": "Biotech", "turnover": 420, "limit_up_count": 0, "avg_change_pct": -1.1, "relative_volume": 0.76},
        ],
        "stocks": [
            {
                "symbol": "3550",
                "name": "聯穎",
                "sector": "AI Server",
                "close": 143.5,
                "ma20": 132.1,
                "volume_ratio": 2.4,
                "rsi": 68,
                "macd_hist": 0.82,
                "institutional_buy_days": 4,
                "revenue_yoy": 28.4,
                "eps_ttm": 5.2,
                "gross_margin": 25.1,
            },
            {
                "symbol": "3017",
                "name": "奇鋐",
                "sector": "AI Server",
                "close": 642,
                "ma20": 610,
                "volume_ratio": 1.9,
                "rsi": 64,
                "macd_hist": 1.18,
                "institutional_buy_days": 3,
                "revenue_yoy": 18.7,
                "eps_ttm": 21.4,
                "gross_margin": 23.6,
            },
            {
                "symbol": "6218",
                "name": "豪勉",
                "sector": "Biotech",
                "close": 42.1,
                "ma20": 44.8,
                "volume_ratio": 0.82,
                "rsi": 42,
                "macd_hist": -0.18,
                "institutional_buy_days": -2,
                "revenue_yoy": -12.6,
                "eps_ttm": 0.3,
                "gross_margin": 12.9,
            },
            {
                "symbol": "2330",
                "name": "台積電",
                "sector": "Semiconductor",
                "close": 872,
                "ma20": 850,
                "volume_ratio": 1.15,
                "rsi": 59,
                "macd_hist": 0.35,
                "institutional_buy_days": 2,
                "revenue_yoy": 16.2,
                "eps_ttm": 39.1,
                "gross_margin": 53.4,
            },
            {
                "symbol": "2382",
                "name": "廣達",
                "sector": "AI Server",
                "close": 286,
                "ma20": 278,
                "volume_ratio": 1.32,
                "rsi": 57,
                "macd_hist": 0.22,
                "institutional_buy_days": 1,
                "revenue_yoy": 9.5,
                "eps_ttm": 12.2,
                "gross_margin": 7.3,
            },
            {
                "symbol": "8046",
                "name": "南電",
                "sector": "PCB",
                "close": 172.5,
                "ma20": 164.2,
                "volume_ratio": 1.7,
                "rsi": 61,
                "macd_hist": 0.44,
                "institutional_buy_days": 2,
                "revenue_yoy": 11.8,
                "eps_ttm": 4.8,
                "gross_margin": 18.4,
            },
        ],
    }
